version: '3.0'
services:
  postgres:
    image: kiasaki/alpine-postgres
    ports:
      - 39008:5432
    environment:
      POSTGRES_USER: vic
      POSTGRES_PASSWORD: liu
      POSTGRES_DB: stocks
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/run:/run/postgresql
      - ./:/data
  puppeteer:
    image: hexxa/puppeteer-alpine
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - ./:/data
    environment:
      # POSTGRES_HOST: 172.16.50.41:39008
      # POSTGRES_HOST: 192.168.31.226:39008
      # POSTGRES_HOST: 192.168.10.137:39008
      POSTGRES_HOST: 192.168.10.221:39008
      POSTGRES_USER: vic
      POSTGRES_PASSWORD: liu
    depends_on:
      - postgres
    command:
      node --inspect=0.0.0.0:9229 /data/index.js
