version: '3.0'
services:
  mysql:
    image: pluie/alpine-mysql
    ports:
      - 39009:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: stocks
      MYSQL_USER: vic
      MYSQL_PASSWORD: liu
    volumes:
      - ./data/mysql:/var/lib/mysql
