version: '3.0'
services:
  mysql:
    image: pluie/alpine-mysql
    ports:
      - 39009:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: stocks
      MYSQL_USER: vic
      MYSQL_PASSWORD: liu
    volumes:
      - ./data/mysql:/var/lib/mysql
  postgres:
    image: kiasaki/alpine-postgres
    ports:
      - 39008:5432
    environment:
      POSTGRES_USER: vic
      POSTGRES_PASSWORD: liu
      POSTGRES_DB: stocks
      #PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
      - ./data/postgres/run:/run/postgresql
  puppeteer:
    image: hexxa/puppeteer-alpine
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - ./:/data
    depends_on:
      - mysql
      - postgres
    command:
      node --inspect=0.0.0.0:9229 /data/index.js
